<?php

namespace AppBundle\Repository;

/**
 * BookingTreatmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingTreatmentRepository extends \Doctrine\ORM\EntityRepository
{
}
