<?php

namespace AppBundle\Repository;

/**
 * ClinicDoctorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClinicDoctorRepository extends \Doctrine\ORM\EntityRepository
{
}
