<?php

namespace AppBundle\Repository;

/**
 * DoctorTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctorTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
