<?php

namespace AppBundle\Repository;

/**
 * DoctorTreatmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctorTreatmentRepository extends \Doctrine\ORM\EntityRepository
{
}
