<?php

namespace AppBundle\Repository;

/**
 * DoctorSpecializationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctorSpecializationRepository extends \Doctrine\ORM\EntityRepository
{
}
