<?php

namespace AppBundle\Repository;

/**
 * TreatmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreatmentRepository extends \Doctrine\ORM\EntityRepository
{
}
