# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        my_db_provider:
            entity:
                class: AppBundle\Entity\User
                #property: email

        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: my_db_provider
            switch_user: true

            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: account_index

            logout:
                path: security_logout
                target: /
                handlers: 
                    - 'app.logout_listener'

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN,ROLE_OBSERVER] }
        - { path: ^/account/doctor, roles: ROLE_DOCTOR }
        - { path: ^/account/hospital, roles: ROLE_HOSPITAL }
        - { path: ^/account, roles: IS_AUTHENTICATED_FULLY }


    role_hierarchy:
       
        ROLE_DOCTOR: ROLE_DOCTOR
        ROLE_HOSPITAL: ROLE_HOSPITAL
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
